//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        [Display(Name = "Mã sản phẩm")]
        public int MaSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string TenSP { get; set; }
        [Display(Name = "Giá")]
        [Range(1,9999999999999999999,ErrorMessage = "Giá không thể nhỏ hơn 1 VNĐ")]
        public Nullable<decimal> DonGia { get; set; }
        [Display(Name = "Ngày cập nhật")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayCapNhap { get; set; }
        [Display(Name = "Cấu hình")]
        public string CauHinh { get; set; }
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
        [Display(Name = "Hình ảnh")]
        public string HinhAnh { get; set; }
        [Display(Name = "Số lượng tồn")]
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Lượt xem")]
        public Nullable<int> LuotXem { get; set; }
        [Display(Name = "Lượt bình chọn")]
        public Nullable<int> LuotBinhChon { get; set; }
        [Display(Name = "Lượt bình luận")]
        public Nullable<int> LuotBinhLuan { get; set; }
        [Display(Name = "Số lần mua")]
        public Nullable<int> SoLanMua { get; set; }
        [Display(Name = "Mới")]
        public Nullable<int> Moi { get; set; }
        [Display(Name = "Mã nhà cung cấp")]
        public Nullable<int> MaNCC { get; set; }
        [Display(Name = "Mã nhà sản xuất")]
        public Nullable<int> MaNSX { get; set; }
        [Display(Name = "Mã loại sản phẩm")]
        public Nullable<int> MaLoaiSP { get; set; }
        [Display(Name = "Đã xóa")]
        public Nullable<bool> DaXoa { get; set; }
        [Display(Name = "Ảnh 1")]
        public string HinhAnh1 { get; set; }
        [Display(Name = "Ảnh 2")]
        public string HinhAnh2 { get; set; }
        [Display(Name = "Ảnh 3")]
        public string HinhAnh3 { get; set; }
        [Display(Name = "Ảnh 4")]
        public string HinhAnh4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        [Display(Name = "Loại sản phẩm")]
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [Display(Name = "Nhà cung cấp")]
        public virtual NhaCungCap NhaCungCap { get; set; }
        [Display(Name = "Nhà sản xuất")]
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
